// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdhwdnwwnariepnvicyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkaHdkbnd3bmFyaWVwbnZpY3l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNzczNjgsImV4cCI6MjA1NDk1MzM2OH0.XIi3bS8GdrGSI83FBm4c-aBOw7JMqQCPzR7LWG8ONLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);